displayName: Travel Expense Refund
schemaName: cr915_expensepilot
accessControlPolicy: Any
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cr915_expensepilot.gpt.default

  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: true
    contentModeration: High
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2025-10-28T17:33:41.0000000Z
template: default-2.1.0
language: 1033